### PR TITLE
Create "elli?".md

### PR DESCRIPTION
**Pull request by raiph**
Notes explaining name / content in the file.

### CODE REVIEW

**Review by JJ — COMMENTED** [review]
This person was effectively working for Summer of Code, tutored by Amanda, name of Madeleine. Not very active afterwards. But what is exactly what you are looking for?

**Comment by raiph** [comment]
Thanks @lizmat, feel free to ignore this comment.

Thanks @JJ, please also feel free to ignore this comment, but to try keep relevant info in one place (this repo) I'll elaborate.

> This person was effectively working for Summer of Code

I knew that bit...

> tutored by Amanda

I didn't know that bit (I had read that tbrowder was the official _mentor_ but I kinda glossed the original GSoC application).

> name of ...

I was obviously too subtle!

As I noted (in the file), all references to that name in the content on the blog they wrote about this GSoC project have been changed to another name (Elli). I interpreted Elli as a non-gender specific name.

While that aspect of the change was perhaps accidental, it was also perhaps deliberate. And while I don't know _why_ the name change has been made, and while one very plausible explanation is that it was changed by an attack bot so the change is _not_ to be respected, another very plausible explanation is that it was changed by the original author, and that the change _was_ to be respected.

> Not very active afterwards.

Right. I knew that.

> But what is exactly what you are looking for?

To appropriately react to discovering that the blog, and thus its contents, are plausibly at imminent risk of disappearing, coupled with knowing that the Internet Archive is also plausibly at imminent risk of disappearing, coupled with feeling that "Elli?"'s GSoC progress, and the blog posts they wrote about it, remain very valuable to Raku.

As I cast about for what to do, I had the thought that CCR might be about the best solution from a pragmatic perspective (despite it being a weak CCR candidate at best given what I understood to be the overall original intent of CCR).

I decided to do a PR and see what happened. At worst Liz could reject it, but at least this stuff would be on record. As it happens Liz has merged it, perhaps understanding it's somewhat an abuse of CCR, but that sometimes even abuse of a technical system is ultimately still a fair use.

**Comment by JJ** [comment]
It's probably the best, you are right. Thanks for the clarification.

**Comment by lizmat** [comment]
FWIW, I think *any* positive blog post about what is now the Raku Programming Language, is fit for the CCR.  And I'm in two minds with regards to any negative blog posts.

**Pull request merged**
